language: python

# Run jobs on container-based infrastructure, can be overridden per job
dist: trusty

matrix:
  include:
    - os: linux
      python: 3.6
      env: PYTHON_VER=3.6
    - os: linux
      python: 3.5
      env: PYTHON_VER=3.5

before_install:
  # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

  # Install the Python environemt
  - source devtools/travis-ci/before_install.sh
  - python -V

install:

    # Create test environment for package
  - conda env create -n test python=$PYTHON_VER -f devtools/conda-envs/psi.yaml
  - source activate test

    # Build and install package
  - bash devtools/travis-ci/install-cctools-62.sh
  - python setup.py develop --no-deps

    # Print versions
  - python -c "import geometric; print(geometric.__version__)"

script:
  - travis_wait 100 pytest -v --cov=torsiondrive torsiondrive/tests/

notifications:
    email: false

after_success:
  - codecov
