language: python

# Run jobs on container-based infrastructure, can be overridden per job
dist: trusty

matrix:
  include:
    - os: linux
      python: 3.6
      env: PYTHON_VER=3.6

before_install:
  # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

  # Install the Python environemt
  - source devtools/travis-ci/before_install.sh
  - python -V

install:

    # Create test environment for package
  - conda env create -n test python=$PYTHON_VER -f devtools/conda-envs/psi.yaml
  - source activate test

    # Build and install package
  - bash devtools/travis-ci/install_geomeTRIC.sh
  - bash devtools/travis-ci/install-cctools-62.sh
  - python setup.py install

script:
  - travis wait 30 pytest -v --cov=crank crank/tests/

notifications:
    email: false

after_success:
  - codecov
